### ISSUE TITLE
View:icon for point data

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/publish#51]
Allow the user to select an argument `icon` when working with point data. It should be a string with some pre-defined icons. Think about using a user-defined file as well.

**Comment by hguerra** [comment]
The icons were taken from https://mapicons.mapsmarker.com/

**Comment by hguerra** [comment]
[mapiconscollection-markers.zip](https://github.com/TerraME/publish/files/742067/mapiconscollection-markers.zip)
