### ISSUE TITLE
Update Arapiuns example with new features View:icon and View:report

### ISSUE THREAD

**Issue by hguerra** [TerraME/publish#81]
- change `beginning` and `ending` color
- insert Application description
- insert new properties in `villages`

**Comment by pedro-andrade-inpe** [comment]
![arapiuns-report](https://cloud.githubusercontent.com/assets/8777631/21939424/de4d0160-d9a6-11e6-9735-7ca454b5fcaa.png)

**Comment by pedro-andrade-inpe** [comment]
http://www.dpi.inpe.br/Miguel/UrbisAmazonia/Apresentacoes/Escada_et_al_RelTecnico_CampoArapiuns_URBIS_2013.pdf
